version: '2'
services:
  test:
    build: .
    image: dovetailbyteslambda
    command: test
    volumes:
      - ./index.js:/app/index.js
      - ./index.test.js:/app/index.test.js
      - ./package.json:/app/package.json
